default: &default
  adapter: mysql2
  database: portfolio
  username: root
  password: password
  host: 127.0.0.1
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>