 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/word_of_mouths", type: :request do
  
  # WordOfMouth. As you add validations to WordOfMouth, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WordOfMouth.create! valid_attributes
      get word_of_mouths_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      word_of_mouth = WordOfMouth.create! valid_attributes
      get word_of_mouth_url(word_of_mouth)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_word_of_mouth_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      word_of_mouth = WordOfMouth.create! valid_attributes
      get edit_word_of_mouth_url(word_of_mouth)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WordOfMouth" do
        expect {
          post word_of_mouths_url, params: { word_of_mouth: valid_attributes }
        }.to change(WordOfMouth, :count).by(1)
      end

      it "redirects to the created word_of_mouth" do
        post word_of_mouths_url, params: { word_of_mouth: valid_attributes }
        expect(response).to redirect_to(word_of_mouth_url(WordOfMouth.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WordOfMouth" do
        expect {
          post word_of_mouths_url, params: { word_of_mouth: invalid_attributes }
        }.to change(WordOfMouth, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post word_of_mouths_url, params: { word_of_mouth: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested word_of_mouth" do
        word_of_mouth = WordOfMouth.create! valid_attributes
        patch word_of_mouth_url(word_of_mouth), params: { word_of_mouth: new_attributes }
        word_of_mouth.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the word_of_mouth" do
        word_of_mouth = WordOfMouth.create! valid_attributes
        patch word_of_mouth_url(word_of_mouth), params: { word_of_mouth: new_attributes }
        word_of_mouth.reload
        expect(response).to redirect_to(word_of_mouth_url(word_of_mouth))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        word_of_mouth = WordOfMouth.create! valid_attributes
        patch word_of_mouth_url(word_of_mouth), params: { word_of_mouth: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested word_of_mouth" do
      word_of_mouth = WordOfMouth.create! valid_attributes
      expect {
        delete word_of_mouth_url(word_of_mouth)
      }.to change(WordOfMouth, :count).by(-1)
    end

    it "redirects to the word_of_mouths list" do
      word_of_mouth = WordOfMouth.create! valid_attributes
      delete word_of_mouth_url(word_of_mouth)
      expect(response).to redirect_to(word_of_mouths_url)
    end
  end
end
