version: '3.8'

services:
  db:
    sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    # environment:
    #  MYSQL_USER: user
     # MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/portfolio/
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mysql_data: